print('Hello word!')
print("What is your name?")
name = input()
print('it is good to meet you ' + name)
print("the length of your name is:")
print(len(name))
print('What is your age?')
myAge = input()
print('You will be '+ str(int(myAge) + 1 ) + ' in a year!')